### PR TITLE
Check if translation file is empty

### PR DESCRIPTION
**Pull request by goesredy**

### CODE REVIEW

**Comment by thiagocordeiro** [comment]
Available on v0.1.3

**Comment by goesredy** [comment]
Thanks

**Comment by thiagocordeiro** [comment]
Sorry, I have to revert it, if for some reason the json is invalid it will be null and erase all older values

**Comment by goesredy** [comment]
Maybe another way to check that ?
Because if json is invalid, the update function will never work

**Comment by thiagocordeiro** [comment]
we can check if file is empty, then it's fine to continue, but if it's not valid and not empty it should stop the process and throw an exception

**Pull request merged**
