### PR TITLE
Customize directories

### PR DESCRIPTION
**Pull request by irineujunior**
Allow to customize the views and language folders

Thanks for the package

### CODE REVIEW

**Comment by thiagocordeiro** [comment]
Nice changes :D, could you also write/explain on readme how to configure different directories?

**Comment by irineujunior** [comment]
Actually, we have a separated package (mixdinternet/frontend) for each site.
So, when we need update the laravel/laravel, its easy to move it.
image

That's the same idea from this package, used by AsgardCMS
https://github.com/nWidart/laravel-modules

Thanks for your time.

**Comment by thiagocordeiro** [comment]
@irineujunior yes, this is a great feature, I just think we should provide an example on readme, then anyone that need it would follow the example

**Comment by irineujunior** [comment]
README updated. =)

**Pull request merged**
