### PR TITLE
Add option to use default language keys as value

### LINKED ISSUE #34: Translation as Default Value
Is it possible to assign a default value to the translation somehow? Maybe a flag (suggestion: "useKeysAsDefaultValue")? 

Laravel, for example, gives us the option to use keys instead of the translation itself, as keys of the JSON translation files. Because of this, libraries which automatically translate JSON files relies in the value, not the key, to then generate automatically translated files (https://github.com/fkirc/attranslate as an example).

I did not found any setting which would allow me to have the Translation as both, key and default value, so i could then use this JSON file as an entry point to generate the localised JSON's in other languages.

**TL:DR**
Is it possible to have a flag which allows me to generate a JSON:
`
{
     "First Message Translated": "First Message Translated",
     "Second Message Translated": "Second Message Translated",
     "Third Message Translated": "Third Message Translated",
}
`

Instead of the current:
`
{
     "First Message Translated": "",
     "Second Message Translated": "",
     "Third Message Translated": "",
}
`

### PR DESCRIPTION
**Pull request by mbardelmeijer**
This PR adds the option to define the option `use_keys_as_default_value`. This will set the key to the value for the `default_language` set (by default, `en`). 

Discussed in #34

Closes #34

### CODE REVIEW

**Comment by thiagocordeiro** [comment]
@mbardelmeijer thanks for the contribution, tests failed and you can have a look at the [report](https://github.com/thiagocordeiro/laravel-translator/runs/7022155833?check_suite_focus=true).

As soon as it passes I'll create a new version for the changes.

Cheers,

**Comment by mbardelmeijer** [comment]
@thiagocordeiro have pushed the necessary code style changes. Tests are green locally, so perhaps with these code style changes, the workflow continues?

**Comment by thiagocordeiro** [comment]
@mbardelmeijer I've changed actions config to run the workflow automatically, however you can run all tests with `composer tests` script

**Comment by mbardelmeijer** [comment]
@thiagocordeiro thanks! Yeah, I'm running it locally but passes fully there, so it's a bit weird why it does return errors in the CI. Will look into it.

**Comment by mbardelmeijer** [comment]
@thiagocordeiro should be good now!

**Comment by thiagocordeiro** [comment]
@mbardelmeijer that's weird. Maybe you have composer dependencies outdated, anyway, since it is green now I've merged already, thanks a lot for contributing 😃

**Pull request merged**
